spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: warehouse_route
          uri: lb://mall-warehouse
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: host_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: mall_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.gulimall.com

        - id: mall_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.gulimall.com

        - id: mall_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.gulimall.com

        - id: mall_order_route
          uri: lb://mall-order
          predicates:
            - Host=order.gulimall.com

        - id: mall_member_route
          uri: lb://mall-member
          predicates:
            - Host=member.gulimall.com

        - id: mall_promotion_route
          uri: lb://mall-promotion
          predicates:
            - Host=seckill.gulimall.com